### ISSUE TITLE
Error: FileNotFoundError: [Errno 2] No such file or directory: 'csv_files/Coswara_positive_heavy_dataset.csv'

### ISSUE THREAD

**Issue by bagustris** [zanjabil2502/Experiment#2]
Mas @zanjabil2502 , saya coba replikasi eksperimen ini tapi muncul error pada step kedua (`2_Create_CSV_Files.py`)

```
s3prl-pt38) pc060066:CCS-experiment$ python 2_Create_CSV_Files.py 
100%|███████████████████████████████████████████████████████████████████████████████████████| 2133/2133 [00:09<00:00, 218.12it/s]
['healthy', 'no_resp_illness_exposed', 'positive_mild', 'positive_asymp', 'recovered_full', 'positive_moderate', 'resp_illness_not_identified']
100%|███████████████████████████████████████████████████████████████████████████████████████| 2217/2217 [00:10<00:00, 209.69it/s]
['symptomatic', 'healthy', 'COVID-19']
725it [00:01, 704.25it/s]
Traceback (most recent call last):
  File "2_Create_CSV_Files.py", line 111, in <module>
    PosData = pd.read_csv('csv_files/Coswara_positive_heavy_dataset.csv')
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/bagus/.local/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'csv_files/Coswara_positive_heavy_dataset.csv'
```

Ada yang terlewat sepertinya sebelum memanggil file csv berikut, 
```
PosData = pd.read_csv('csv_files/Coswara_positive_heavy_dataset.csv')
```
File `Coswara_positive_heavy_dataset.csv` tidak ada dan belum pernah di-generate sebelumnya (tidak juga ada di step 1).

Mohon konfirmasinya.

**Comment by zanjabil2502** [comment]
Sudah saya fix programnya dan sudah saya update reponya, mungkin bisa di run dari lagi bapak dari awal

**Comment by bagustris** [comment]
Masih ada error Mas @zanjabil2502 ,
Cek baris, berikut,`Pos_Data` , `PosData`, dan `Posvid_Data` belum pernah didefinisikan, tapi sudah dipanggil:

```
MergeData = pd.concat([Pos_Data, PosData, Posvid_Data, CompData])
MergeData   = MergeData.sample(frac=1).reset_index(drop=True)
```
Error yang ditampilkan akan seperti ini, 

```
725it [00:01, 715.70it/s]
Traceback (most recent call last):
  File "2_Create_CSV_Files.py", line 149, in <module>
    MergeData = pd.concat([Pos_Data, PosData, Posvid_Data, CompData])
NameError: name 'Pos_Data' is not defined
```
Jika menggunakan jupyter, sebaiknya dilakukan sekali run, tidak per baris acak. Atau kalau kalau perbaris, pastikan urut dari baris pertama sampai terakhir tidak ada error (lagi, tidak acak atau loncat atau balik ke baris selanjutnya).

**Comment by zanjabil2502** [comment]
Baik bapak, sudah saya perbaiki lagi, mohon maaf sebelumnya karena waktu perbaikan program saya tidak run ulang, dikarenakan saya perbaiki dari pc yang berbeda bapak, jadi saya hanya cek ulang program dengan melihat 1 per 1 bapak.

**Comment by bagustris** [comment]
OK, mas @zanjabil2502.  Saya lanjut ke step 3.
